<a href="https://colab.research.google.com/github/SanLoveCode/30days_of_ml202207_San/blob/main/30daysML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [7]:
import pandas as pd

train_cn = pd.read_excel('/content/drive/My Drive/汽车领域多语种迁移学习挑战赛初赛训练集/中文_trian.xlsx')
train_ja = pd.read_excel('/content/drive/My Drive/汽车领域多语种迁移学习挑战赛初赛训练集/日语_train.xlsx')
train_en = pd.read_excel('/content/drive/My Drive/汽车领域多语种迁移学习挑战赛初赛训练集/英文_train.xlsx')
test_ja = pd.read_excel('/content/drive/My Drive/汽车领域多语种迁移学习挑战赛初赛训练集/testA.xlsx', sheet_name='日语_testA')
test_en = pd.read_excel('/content/drive/My Drive/汽车领域多语种迁移学习挑战赛初赛训练集/testA.xlsx', sheet_name='英文_testA')

In [ ]:
# 训练集和测试集字段类型，并将数据读取代码写到博客

In [15]:
# 查看训练集和测试集的大小
print("Training entries: {}, test entries: {}".format(len(train_cn), len(train_cn)))
print("Training entries: {}, test entries: {}".format(len(train_ja), len(train_ja)))
print("Training entries: {}, test entries: {}".format(len(train_en), len(train_en)))
print("Training entries: {}, test entries: {}".format(len(test_ja), len(test_ja)))

Training entries: 32275, test entries: 32275
Training entries: 1002, test entries: 1002
Training entries: 1001, test entries: 1001
Training entries: 769, test entries: 769

In [16]:
# 查看中文样例
train_cn[:10]

         原始文本                               意图          槽值1  槽值2
0       16.5度  adjust_ac_temperature_to_number  offset:16.5  NaN
1         16度  adjust_ac_temperature_to_number    offset:16  NaN
2   16空调开到16度  adjust_ac_temperature_to_number    offset:16  NaN
3     16温度16度  adjust_ac_temperature_to_number    offset:16  NaN
4         17度  adjust_ac_temperature_to_number    offset:17  NaN
5         18度  adjust_ac_temperature_to_number    offset:18  NaN
6         19度  adjust_ac_temperature_to_number    offset:19  NaN
7         20度  adjust_ac_temperature_to_number    offset:20  NaN
8  20小微你调到26度  adjust_ac_temperature_to_number    offset:26  NaN
9         21度  adjust_ac_temperature_to_number    offset:21  NaN

In [17]:
# 查看日文样例
test_ja[:10]

            原始文本
0       エアコンをつける
1        エアコン付ける
2   エアコンをつけてください
3       エアコンをONに
4           エアコン
5        エアコンの電源
6   エアコンのスイッチ付ける
7     エアコンの電源をON
8  エアコンをつけてくれますか
9  エアコンをつけてくれないか